plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - workshop.md
  – README.md
  - index.md

theme: 
  jekyll-theme-cayman
title: 
  Workshop at DHN2019
